config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  
  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  
  def index
    @notes = Note.where(user_id: current_user)
  end

  def new
    @note = current_user.notes.build
  end

  def show
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'new'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Notebook 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  %link{:rel => "stylesheet", :href=> "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}>
  = csrf_meta_tags
  
%body
  %header 
    .header_inner
      = link_to image_tag('logo.png', size: "50x50"), root_path, id: "Logo" 
      %nav
        - if user_signed_in?
          = link_to "New Note", new_note_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path
  %p.notice= notice
  %p.alert= alert

  = yield

app/views/notes/_form.html.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/notes/edit.html.haml
.wrapper_with_padding
  %h1 Edit Note

  =render 'form'

  = link_to "Cancel", notes_path

app/views/notes/index.html.haml
.wrapper_with_padding
  #notes.clearfix
    -unless @notes.blank?
      - @notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    -else
      %h2 Add note
      %p You haven't added any notes yet!
      %button= link_to "New Note", new_note_path

app/views/notes/new.html.haml
.wrapper_with_padding
  %h1 Add New Note

  = render 'form'

app/views/notes/show.html.haml
.wrapper_with_padding
  #note_show
    %h1= @note.title
    %p= simple_format(@note.content)

    .buttons
      = link_to "Edit", edit_note_path(@note), class: "button"
      = link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure you want to delete?"}, class: "button"

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 NoteBook
    %p Online notebook for your life!
    %button= link_to "Sign Up", new_user_registration_path

#testimonial
  .wrapper
    %p.quote "Plain Awesome!"
    %p.name ~ Ché

#callouts
  .callout_inner
    .wrapper
      .callout
        %i.fa.fa-pencil
        %h2 Notes
        %p Meditation put a bird on it drinking vinegar organic pickled, Truffaut migas Carles deep v XOXO bespoke semiotics readymade wolf pour-over. Put a bird on it forage seitan, XOXO Helvetica Echo Park sartorial twee. Mixtape cronut disrupt hella hashtag, listicle Bushwick Schlitz hoodie umami small batch irony plaid Truffaut. Photo booth lumbersexual DIY brunch hoodie, trust fund Pinterest. Brunch banh mi twee, trust fund viral chia letterpress jean shorts. Vice kogi meh Portland plaid. Migas tousled wolf polaroid cray before they sold out.
      .callout
        %i.fa.fa-shopping-cart
        %h2 Shopping List
        %p Marfa Godard hashtag chia. Hella salvia Brooklyn raw denim. Stumptown artisan health goth, plaid lomo Etsy chia put a bird on it beard banh mi. Ennui four dollar toast roof party, literally Brooklyn pork belly sriracha. Normcore Pitchfork small batch selfies organic locavore, cornhole fanny pack VHS dreamcatcher listicle Shoreditch art party. Etsy lumbersexual Marfa jean shorts tattooed, polaroid flexitarian. Sartorial fingerstache tousled single-origin coffee, banh mi Neutra fixie normcore taxidermy direct trade VHS.
      .callout
        %i.fa.fa-calendar
        %h2 Schedule
        %p Four dollar toast twee master cleanse, gastropub PBR viral whatever asymmetrical craft beer flexitarian pork belly. Freegan brunch American Apparel chillwave fingerstache, beard stumptown. Gastropub meggings bicycle rights, tattooed street art taxidermy sustainable Carles Vice. Umami messenger bag Banksy, whatever jean shorts cold-pressed meh mumblecore tousled pickled bitters. Selvage yr Kickstarter, kale chips asymmetrical typewriter pork belly sriracha iPhone artisan DIY selfies sustainable mlkshk. Gentrify actually shabby chic, Tumblr tote bag Helvetica chillwave iPhone squid Godard polaroid literally irony. McSweeney's cray selfies Tumblr pork belly skateboard occupy synth cronut ennui 8-bit, forage Shoreditch Kickstarter chia.

#bottom_cta
  .wrapper
    %h2 Hey There
    %p Have access to your notes online!
    %button= link_to "Sign Up", new_user_registration_path

%footer
  %p &copy; 2015 FreeSpirit Development.